# Generated by Django 5.2.4 on 2025-09-07 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cash', models.BooleanField(default=False)),
                ('from_card', models.BooleanField(default=False)),
                ('income_transactions', models.BooleanField(default=False)),
                ('expense_transactions', models.BooleanField(default=False)),
                ('subscriptions', models.BooleanField(default=False)),
                ('compute_statistics_from', models.DateField(blank=True, null=True)),
                ('compute_statistics_to', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('EUR', 'EUR (€)'), ('USD', 'USD ($)'), ('GBP', 'GBP (£)'), ('JPY', 'JPY (¥)'), ('SEK', 'SEK (Kr)'), ('CHF', 'CHF (₣)')], default=('EUR', 'EUR (€)'), max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
