# Generated by Django 5.2.4 on 2025-09-08 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='subscription_last_paid_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription_next_paid_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 9, 8), null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='compute_statistics_from',
            field=models.DateField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='compute_statistics_to',
            field=models.DateField(blank=True, null=True, verbose_name='Until'),
        ),
    ]
