# Generated by Django 5.2.4 on 2025-09-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionsApp', '0002_analytics_delete_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='from_card',
        ),
        migrations.AddField(
            model_name='analytics',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='analytics',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='analytics',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
